### ISSUE TITLE
Better mime type checking

### ISSUE THREAD

**Issue by Dantemss** [openstax/exercises#105]
Carrierwave checks uploaded file mime types based on the extension. It might be preferable for security reasons to instead check them using filemagic. Take a look at https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/magic_mime_whitelist.rb

**Comment by nathanstitt** [comment]
https://github.com/openstax/exercises/pull/103 uses the mime magic gem to detect filetypes by the 'magic' bit fingerprinting.  That should be more reliable than extensions.  I originally used the `filemagic` gem but ran into deployment issues because the libmagic  package wasn't installed.  Rather than create additional deployment steps, I researched a bit more and found `mimemagic`.  Seems to do the same thing as `filemagic` without a reliance on system libs.
